begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  birth_date date,
  address text not null default '',
  phone text not null default '',
  email text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cognitive_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  score integer not null check (score >= 0),
  risk text not null,
  answers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.chronic_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  age integer not null check (age between 1 and 130),
  systolic integer not null check (systolic between 40 and 300),
  diastolic integer not null check (diastolic between 20 and 200),
  blood_sugar integer not null check (blood_sugar between 20 and 800),
  sugar_timing text not null check (sugar_timing in ('fasting', 'after_meal', 'random')),
  created_at timestamptz not null default now()
);

create table if not exists public.practice_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  practice_date date not null default current_date,
  checks jsonb not null default '{}'::jsonb,
  completed_count integer not null default 0 check (completed_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, practice_date)
);

create index if not exists cognitive_records_user_created_idx on public.cognitive_records(user_id, created_at desc);
create index if not exists chronic_records_user_created_idx on public.chronic_records(user_id, created_at desc);
create index if not exists practice_records_user_date_idx on public.practice_records(user_id, practice_date desc);

alter table public.profiles enable row level security;
alter table public.cognitive_records enable row level security;
alter table public.chronic_records enable row level security;
alter table public.practice_records enable row level security;

revoke all on table public.profiles, public.cognitive_records, public.chronic_records, public.practice_records from anon;
grant select, insert, update, delete on table public.profiles, public.cognitive_records, public.chronic_records, public.practice_records to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "members manage own profile" on public.profiles;
create policy "members manage own profile" on public.profiles
  for all to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "members manage own cognitive records" on public.cognitive_records;
create policy "members manage own cognitive records" on public.cognitive_records
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "members manage own chronic records" on public.chronic_records;
create policy "members manage own chronic records" on public.chronic_records
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "members manage own practice records" on public.practice_records;
create policy "members manage own practice records" on public.practice_records
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, name, birth_date, address, phone, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    nullif(new.raw_user_meta_data ->> 'birth_date', '')::date,
    coalesce(new.raw_user_meta_data ->> 'address', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(new.email, '')
  )
  on conflict (id) do update set
    name = excluded.name,
    birth_date = excluded.birth_date,
    address = excluded.address,
    phone = excluded.phone,
    email = excluded.email,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of raw_user_meta_data, email on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.delete_current_user()
returns void
language sql
security definer set search_path = ''
as $$
  delete from auth.users where id = (select auth.uid());
$$;

revoke all on function public.delete_current_user() from public;
grant execute on function public.delete_current_user() to authenticated;

commit;
